config/routes.rb
Rails.application.routes.draw do
  get 'price', to: 'main_page#price'
  get 'vacancy', to: 'job_opening#vacancy'
  devise_for :users
  get 'main_page/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main_page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_opening_controller.rb
class JobOpeningController < ApplicationController
  def vacancy
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_opening_helper.rb
module JobOpeningHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/job_opening/vacancy.html.haml
.container-fluid.borders.rounded
    .row.justify-content-center
        .col-12.col-sm-12.col-md-8.col-lg-8.col-xl-8.bg_grid.rounded-left.border-right
            .list-group.pt-4.pb-4
                %a.list-group-item.list-group-item-action
                    .d-flex.w-100.justify-content-between
                        %h5.mb-1
                            Маляр
                        %small.text-success
                            актуально
                    %p.mb-1.bg-primary
                        Оплата сдельная, до 50% от выработки
                        %sup
                            *
                %a.list-group-item.list-group-item-action
                    .d-flex.w-100.justify-content-between
                        %h5.mb-1
                            Автомеханик
                        %small.text-success
                            актуально
                    %p.mb-1.bg-primary
                        Оплата сдельная, до 50% от выработки
                        %sup 
                            *
                %a.list-group-item.list-group-item-action
                    .d-flex.w-100.justify-content-between
                        %h5.mb-1
                            Менеджер по запчастям
                        %small.text-success
                            актуально
                    %p.mb-1.bg-warning
                        Оклад + % от выработки
                        %sup
                            *
                    %small
                        %sup
                            **
                        по результатам собеседования

app/views/layouts/_footer.html.haml
.container-fluid.mt-1
    .row.justify-content-center
        .col-12.col-sm-12.col-md-8.col-lg-8.col-xl-8.bg_grid.borders.rounded
            %p.text-white
                Контакты:
            %p.text-white
                +7(905)706-45-45
            %p.text-white
                +7(926)876-71-49
            %p.text-white
                Москва, Улица Щербинская, дом 48А стр. 11

app/views/layouts/_header.html.haml
.container-fluid.borders.rounded.mb-1
    .row.justify-content-center
        .col-12.col-sm-12.col-md-8.col-lg-8.col-xl-8.bg
            = link_to root_path do
                = image_tag("logo.png", class: "logo")
            /"#{image_tag("logo.png", class: "logo")}", root_path
            /((image_tag "logo.png"), root_path), :class => 'logo'
            = image_tag "tagline.png", :class => "tagline"
    .row.justify-content-center
        .col-12.col-sm-12.col-md-8.col-lg-8.col-xl-8.bg_grid.rounded-bottom.d-flex
            .col-5.d-inline
                %p.phone-number +7(905)706-45-45
                %p.phone-number +7(965)142-20-14
                %p.phone-number +7(926)876-71-49
            .col-2
            .col-5.d-inline
                %p.work-time 8:00 - 20:00
                %p.phone-number.text-danger Мы работаем!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>EG-Motors Car</title>
  <meta name="yandex-verification" content="58698df5353327b9" />
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
      (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
      m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
      (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

      ym(54857494, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
      });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/54857494" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
  </head>

  <body class = "body">
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/main_page/index.html.haml
.container-fluid.borders.rounded
    .row.justify-content-center
        .col-4.col-sm-4.col-md-2.col-lg-2.col-xl-2.bg_grid.rounded-left.border-right
            .row
                .col.sales
                    %p.sale.text-center
                        %a Акции
                    %ul
                        %li.text-light.sale-li{:"data-toggle" => "tooltip", :"data-placement" => "top", :title => "Распространяеться только на работы. Не распростроняется на запчасти и прочие товары."}
                            скидки до 20% до 31 мая! 
                            %sup *
                        %li.text-light.sale-li{:"data-toggle" => "tooltip", :"data-placement" => "top", :title => "Только при условии обслуживания в нашем сервис-центре и стоимости эвакуации до 3000 рублей"}
                            Эвакуатор бесплатно!
                            %sup **
                        %li.text-light.sale-li{:"data-toggle" => "tooltip", :"data-placement" => "top", :title => "Только при условии дальнейшего обслуживания в нашем сервис-центре!"}
                            Диагностика бесплатно!
                            %sup ***
            .row
                .col
                    %ul.nav.flex-column
                        %li.nav-item
                            = link_to(price_path, class: "nav-link text-light") do
                                Виды ремонтов и цены
                        %li.nav-item
                            %a.nav-link.text-light Запчасти
                        %li.nav-item
                            = link_to(vacancy_path, class: "nav-link text-light") do
                                Вакансии
                        %li.nav-item
                            %a.nav-link.text-light Партнеры
                        %li.nav-item
                            %a.nav-link.text-light О нас
        .col-8.col-sm-8.col-md-6.col-lg-6.col-xl-6.bg_grid.rounded-right.border-left
            /
                .row
                    .col
                        %p.font-4rem.text-light.text-center Мультибренд
                .row
                    .col
                        %p.font-3rem.text-light.text-center Все виды ремонтов
                        %p.font-3rem.text-light.text-center Вашего Авто
            .row
                .carousel.slide#CarouselMainPage{:"data-ride" => "carousel"}
                    .carousel-inner
                        .carousel-item.carousel-item-size
                            %img.d-block.w-100.img-fluid{:src => image_url("multbrand"), :alt => "Мультибренд"}
                            .carousel-caption.d-none.d-md-block
                                %p.carousel-text Мультибренд
                        .carousel-item.carousel-item-size
                            %img.d-block.w-100.img-fluid{:src => image_url("kuzremont"), :alt => "Кузовной ремонт"}
                            .carousel-caption.d-none.d-md-block
                                %p.carousel-text Кузовной ремонт
                        .carousel-item.carousel-item-size
                            %img.d-block.w-100.img-fluid{:src => image_url("raptor"), :alt => "Покраска раптором"}
                            .carousel-caption.d-none.d-md-block
                                %p.carousel-text Покраска раптором
                        .carousel-item.carousel-item-size.active
                            %img.d-block.w-100.img-fluid{:src => image_url("VseVidyRemontov"), :alt => "Все виды ремонтов"}
                            .carousel-caption.d-none.d-md-block
                                %p.carousel-text Все виды ремонтов

                    %a.carousel-control-prev{"data-slide" => "prev", :href => "#CarouselMainPage", :role => "button"}
                        %span.carousel-control-prev-icon{"aria-hidden" => "true"}
                        %span.sr-only Previous
                    %a.carousel-control-next{"data-slide" => "next", :href => "#CarouselMainPage", :role => "button"}
                        %span.carousel-control-next-icon{"aria-hidden" => "true"}
                        %span.sr-only Next

            .row
                .col.border-top.border-bottom.p-0
                    %script{:type => "text/javascript",
                            :src => "https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A6dee49d8f293cffadf44cb6a249b23a9f484ab984e702fd409304d4e1844cd17&amp;width=100%25&amp;height=499&amp;lang=ru_RU&amp;scroll=true"}
            .row
                .col
                    %span.text-light Отзывы

app/views/main_page/price.html.haml
.container-fluid.borders.rounded
    .row.justify-content-center
        .col-12.col-sm-12.col-md-8.col-lg-8.col-xl-8.bg_grid.rounded-left.border-right
            %embed{:src => "price.pdf", :width => 800, :height => 1000, :style => "border: none"}